# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import translation_pb2 as translation__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in translation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TranslationEngineStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranslateText = channel.unary_unary(
                '/translation.TranslationEngine/TranslateText',
                request_serializer=translation__pb2.TranslateRequest.SerializeToString,
                response_deserializer=translation__pb2.TranslateReply.FromString,
                _registered_method=True)
        self.GetSupportedLanguages = channel.unary_unary(
                '/translation.TranslationEngine/GetSupportedLanguages',
                request_serializer=translation__pb2.GetLanguagesRequest.SerializeToString,
                response_deserializer=translation__pb2.GetLanguagesReply.FromString,
                _registered_method=True)


class TranslationEngineServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TranslateText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSupportedLanguages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TranslationEngineServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranslateText': grpc.unary_unary_rpc_method_handler(
                    servicer.TranslateText,
                    request_deserializer=translation__pb2.TranslateRequest.FromString,
                    response_serializer=translation__pb2.TranslateReply.SerializeToString,
            ),
            'GetSupportedLanguages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSupportedLanguages,
                    request_deserializer=translation__pb2.GetLanguagesRequest.FromString,
                    response_serializer=translation__pb2.GetLanguagesReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'translation.TranslationEngine', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('translation.TranslationEngine', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TranslationEngine(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TranslateText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/translation.TranslationEngine/TranslateText',
            translation__pb2.TranslateRequest.SerializeToString,
            translation__pb2.TranslateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSupportedLanguages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/translation.TranslationEngine/GetSupportedLanguages',
            translation__pb2.GetLanguagesRequest.SerializeToString,
            translation__pb2.GetLanguagesReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
