# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: translation.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'translation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11translation.proto\x12\x0btranslation\"J\n\x10TranslateRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x13\n\x0bsource_lang\x18\x02 \x01(\t\x12\x13\n\x0btarget_lang\x18\x03 \x01(\t\"Q\n\x0eTranslateReply\x12\x17\n\x0ftranslated_text\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\"\x15\n\x13GetLanguagesRequest\"=\n\x11GetLanguagesReply\x12(\n\tlanguages\x18\x01 \x03(\x0b\x32\x15.translation.Language\"&\n\x08Language\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t2\xbf\x01\n\x11TranslationEngine\x12M\n\rTranslateText\x12\x1d.translation.TranslateRequest\x1a\x1b.translation.TranslateReply\"\x00\x12[\n\x15GetSupportedLanguages\x12 .translation.GetLanguagesRequest\x1a\x1e.translation.GetLanguagesReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'translation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSLATEREQUEST']._serialized_start=34
  _globals['_TRANSLATEREQUEST']._serialized_end=108
  _globals['_TRANSLATEREPLY']._serialized_start=110
  _globals['_TRANSLATEREPLY']._serialized_end=191
  _globals['_GETLANGUAGESREQUEST']._serialized_start=193
  _globals['_GETLANGUAGESREQUEST']._serialized_end=214
  _globals['_GETLANGUAGESREPLY']._serialized_start=216
  _globals['_GETLANGUAGESREPLY']._serialized_end=277
  _globals['_LANGUAGE']._serialized_start=279
  _globals['_LANGUAGE']._serialized_end=317
  _globals['_TRANSLATIONENGINE']._serialized_start=320
  _globals['_TRANSLATIONENGINE']._serialized_end=511
# @@protoc_insertion_point(module_scope)
